### ISSUE TITLE
Error when running "make"

### ISSUE THREAD

**Issue by idanyani** [technion-csl/mosmodel#14]
$ make
... # a lot of output here
make: *** No rule to make target 'results/linear_models_coeffs/mean.csv', needed by 'analysis/linear_models_coeffs/normalized_scatter.csv'.  Stop.

**Comment by magbarya** [comment]
Fixed in [0eed248](https://github.com/technion-csl/mosmodel/commit/0eed248eedf0963a8516131c44cb7f551a3b0821)
Don't include common analysis makefile in analysis/linear_models_coeffs/module.mk (because linear_models_coeffs module is not built using the common experiment makefile) and include the general common makefile instead.
