### ISSUE TITLE
Not able to ssh access after running toy_benchmark

### ISSUE THREAD

**Issue by akshaybaviskar** [technion-csl/mosmodel#17]
Hello @idanyani and @magbarya ,

I am facing a strange issue, after running make for toy benchmark system gets stuck after sometime.
And then I am not able to ssh into it. However, ping succeeds.
This happened three times in a row. 

I am thinking of other possible causes for this. And I also wanted to bring it to your attention.
Do you think of any possible reason associated with running toy_benchmark for this behavior?

I have attached log for two of the runs.

Thanks,
Akshay
[logbeforehang.txt](https://github.com/technion-csl/mosmodel/files/7106087/logbeforehang.txt)
[logbeforehang2.txt](https://github.com/technion-csl/mosmodel/files/7106089/logbeforehang2.txt)

**Comment by idanyani** [comment]
From the log it seems like the system hangs at random stages of "make" so I suspect that this issue is related to your system rather than to our code...
Did you try to run "make" with other benchmarks? Did you try running the toy_benchmark on another machine?

For example, we faced a similar issue after upgrading from Ubuntu 18 to 20. Apparently, the default power management settings in Ubuntu 20 allow the OS to suspend after several minutes of idleness. You can:
```
$ grep -a  PM: /var/log/syslog.1 /var/log/syslog
```
And check for "PM: suspend entry" in the output.
If this is the issue, you can fix it by adding the following to /etc/systemd/sleep.conf :
```
AllowSuspend=no
AllowHibernation=no
AllowSuspendThenHibernate=no
AllowHybridSleep=no
```

**Comment by akshaybaviskar** [comment]
okay, I am checking. Closing this issue now. Thanks.
